[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/", "@chainlink/contracts/=lib/chainlink/contracts/",
             "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
             "@solmate=lib/solmate/src/"]

solc_version = "0.8.20"
gas_reports = ["LotteryContract", "PauserRegistry"]

# Removes 53 bytes of optional bytecode at end of deployed contract
bytecode_hash = "none"
cbor_metadata = false

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"
arbitrum_goerli = "${RPC_ARBITRUM_GOERLI}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options