name: Coverage

on:
  push:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: ci
  DEPLOYER_ADDRESS: "0xfeACBb053CCcF794bF2810f0D08A46CC52EDBDf3"

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        id: test

    name: Prune coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install lcov
        run: apt-get update && apt-get install lcov -y

      - name: Prune lcov.info
        run: |
          lcov --remove ./lcov.info -o ./lcov.info.pruned 'test/mocks/' 'script/HelperConfig.s.sol' 'script/Interactions.s.sol'

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info




             

            