name: Coverage

on:
  push:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        run: |
          forge coverage
        id: test
        ignore:
          - "./test/"
          - "./script/HelperConfig.s.sol"
          - "./script/Interactions.s.sol"
          - "./src/Interactions.s.sol"


             

            